### ISSUE TITLE
Add a Docker Compose File

### ISSUE THREAD

**Issue by RishiKumarRay** [ankitapuri/pixelvibe#416]
I see a Docker File here, I would like to add on Docker-Compose file , then it would be more convenient to start this application in container, with just one command. Should I go for it, If you want?

**Comment by 7saikat7** [comment]
It's a valid issue, that's why I am assigning you cause participants can't create issues.So please consider discussing issues on discord first then we will create them for u.

1.Add docker.yml properly.
2.Add a screenshot of the image this project running on docker in the PR

**Comment by 7saikat7** [comment]
you are participating through swoc right ?

**Comment by RishiKumarRay** [comment]
No, I came to Know about this project while searching and sorry for not discussing this on Discord First, I will remember this for next time.

**Comment by 7saikat7** [comment]
It's ok , actually, these issues are under swoc , so as of now I am unassigning you ,later you can work on this project

**Comment by RishiKumarRay** [comment]
Ok, one thing i would like to ask, Is registeration still open for swoc and can i work on this issue after getting registered? Just asking

**Comment by ankitapuri** [comment]
> Ok, one thing i would like to ask, Is registeration still open for swoc and can i work on this issue after getting registered? Just asking

no its currently closed

**Comment by 7saikat7** [comment]
It's closed ...there will be one more open source in Jan named JGOC or Jwoc
so u can participate
